<div class="footer">
  <div class="textBox">  		
  		<?php $footerText = Mage::getStoreConfig('dropshipper_options/general_options/footer_text'); 
			   if(!empty($footerText)){
			   		echo $footerText;
			   }else{
			   		echo "Footer Text Not Set!";
			   }
		?>
  </div>
      <div class="footerBlock">
        <h4><?php echo $this->__('Useful Links') ?></h4>
        <?php echo $this->getChildHtml('footer_links') ?>
      </div>
      <div class="footerBlock">
        <h4><?php echo $this->__('My Account') ?></h4>
        <?php echo $this->getLayout()->getBlock('top.links')->toHtml()  ?>   
      </div>
      <div class="footerBlock last">
        <h4><?php echo $this->__('Pages') ?></h4>
        <ul class="links">
        	<?php echo $this->getLayout()->getBlock('cms_pages')->toHtml()  ?>			
      	</ul>
      </div>
  <div class="clear"></div>
</div>
 <p class="credits"><?php echo Mage::getStoreConfig('dropshipper_options/general_options/footer_credits'); ?></p>

<?php /* Crazy Egg Tracking Code in Footer */ ?> 
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0017/4406.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
