<?php
    $store = Mage::app()->getStore();   
    $cms_pages = Mage::getModel('cms/page')->getCollection();
	$cms_pages->getSelect()->where('is_active = 1');
        $last = count($cms_pages);
        $lastText = '';
		//foreach($cms_pages as $_page)
        $ctr = 0; ?>
		
		<li><a href="<?php echo Mage::helper('cms/page')->getPageUrl('comprar')?>">Compra</a></li>
		<li><a href="<?php echo Mage::helper('cms/page')->getPageUrl( 'anunciate ' ) ?> ">Vende</a></li>
     	<li><a href="<?php echo Mage::helper('cms/page')->getPageUrl( 'quienes-somos' ) ?> ">Sobre Nosotros</a></li>
	 <?php /* Code commented by shweta kaushish to display static pages (6 June 2013)
	  foreach($cms_pages as $_page)
        {
            $data = $_page->getData();
            if($data['identifier']=='no-route' || $data['identifier']=='home')
                continue;            
            if(Mage::helper('core/url')->getCurrentUrl()== Mage::getURL('').''.$data['identifier']) {
                $str_active_class    =    "active";
            } else {
                $str_active_class    =    "";
            }            
            if($ctr++ == $last)
                $lastText = ' last';
            echo '<li class="level1'.$lastText.' '.$str_active_class.' '.$data['title'].' " ><a href="'.Mage::getURL('').''.$data['identifier'].'"><span>'.$data['title'].'</span></a></li>'."\n";
        } 
		*/?>
