<?php
/**
 * Product:     Advanced Permissions
 * Package:     Aitoc_Aitpermissions_2.4.0_2.0.3_467174
 * Purchase ID: 3G9mNSuToHcGAqzlcnyFlyU7YfL60ELq65IlLBrb3G
 * Generated:   2013-05-03 18:29:40
 * File path:   app/design/frontend/default/default/template/aitpermissions/lfooter.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php
/**
 * @copyright  Copyright (c) 2009 AITOC, Inc. 
 */
?>
<!-- clodrnngyqwttgmslelmjcfmtpbvvgiy -->