<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
	<table>
		<tr>
			<td><Strong>ID<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</strong></td>
			<td><?php echo $this->_model->getId(); ?></td>
		</tr>
		<tr>
			<td><Strong>Nombre<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</strong></td>
			<td><?php echo $this->_model->getName(); ?></td>
		</tr>
		<tr>
			<td><Strong>E-mail<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</Strong></td>
			<td><?php echo $this->_model->getEmail(); ?><p></p></td>
		</tr>
		<tr>
			<td><Strong>Tel&eacute;fono</Strong></td>
			<td><?php echo $this->_model->getPhone(); ?><p></p></td>
		</tr>
		<tr>
			<td><Strong>Mensaje<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</Strong></td>
			<td><?php echo $this->_model->getMessage(); ?><p></p></td>
		</tr>
		<tr>
			<td><Strong>Product<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</Strong></td>
			<td><?php echo $this->getProduct()->getName(); ?><p></p></td>
		</tr>
		<tr>
			<td><Strong>Categories<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</Strong></td>
			<td>
				<?php echo $this->_model->getCategoryName(); ?><br/>
				<?php echo $this->_model->getSubcategoryName(); ?><br/>
				<p></p>
			</td>
		</tr>
	</table>
</div>