<table cellpadding="5" cellspacing="5">
	<tr>
		<td colspan="2">Estimado usuario,<p>{{var name}} ha pedido la siguiente cotización:</p>
		</td>
	</tr>
	<tr><td colspan="2">&nbsp;</td></tr>
	<tr><td colspan="2">==============================================</td></tr>
	<tr><td><b>Nombre de producto:</b></td><td>{{var product_name}}</td></tr>
	<tr><td><b>Nombre de contacto:</b></td><td>{{var name}}</td></tr>
	<tr><td><b>Email:</b></td><td>{{var email}}</td></tr>
	<tr><td><b>Tel:</b></td><td>{{var phone}}</td></tr>
	<tr><td><b>Mensaje:</b></td><td>{{var body}}</td></tr>
	<tr><td colspan="2">&nbsp;</td></tr>
	<tr><td colspan="2">==============================================</td></tr>
</table>
