<?php
/**
 * Product:     Advanced Permissions
 * Package:     Aitoc_Aitpermissions_2.4.0_2.0.3_467174
 * Purchase ID: 3G9mNSuToHcGAqzlcnyFlyU7YfL60ELq65IlLBrb3G
 * Generated:   2013-05-03 18:29:40
 * File path:   app/design/adminhtml/default/default/template/aitpermissions/options.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<br />

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditGlobalAttributes() ? 'checked="checked"' : '' ?>
           name="allowupdateglobalattrs"
           id="allowupdateglobalattrs"
           value="1" />&nbsp;
    <label for="allowupdateglobalattrs">
        <b><?php echo $this->__('Allow update global attributes') ?></b>
    </label>
</div>

<br />

<div style="background-color: whiteSmoke;">
    <input type="checkbox"
        <?php echo $this->canEditOwnProductsOnly() ? 'checked="checked"' : '' ?>
           name="caneditownproductsonly"
           id="caneditownproductsonly"
           value="1" />&nbsp;
    <label for="caneditownproductsonly">
        <b><?php echo $this->__('Allow manage own products only') ?></b>
    </label>
</div>