<?php
    $_helper = $this->helper('catalog/output');
    $_product = Mage::registry('current_product');
?>

<script type="text/javascript">
function polcode_productmessage_validate(){
	var x=document.forms["quickrfq_form"]["contact_name"].value;
	if (x==null || x=="" || x=="Name")
	{  
  	  alert("Por favor dinos tu nombre");
	  document.getElementById('name').focus();
		  return false;
		  }
	  
		 var y=document.forms["quickrfq_form"]["user_email"].value;
		  var atpos=y.indexOf("@");
		 var dotpos=y.lastIndexOf(".");
		 var z=document.forms["quickrfq_form"]["rfq_message"].value;

	if(y==""){
		alert('Por favor dinos tu email');

		document.getElementById('email').focus();
		return false;
	}
				 
	if (y!=""){	
		  if (atpos<1 || dotpos<atpos+2 || dotpos+2>=y.length)
		  {

		  alert("No parece ser un email válido");

		  document.getElementById('email').focus();
		  return false;
		  }
	}
	if(z==""){
		alert('Por favor escribe mensaje/cotización');

		//document.getElementById('rfq_message').focus();
		 return false;
	}
    else{
		//document.getElementById("quickrfq_form").submit();
  		polcode_productmessage_submit();
  	}
  	return false;
}

function polcode_productmessage_submit(){
	document.getElementById('polcode_productMessage_submitButton').disabled = true;
	document.getElementById('polcode_productMessage_submitButton').setAttribute("disabled", "disabled");
	data = $j('#quickrfq_form').serialize();
	$j.ajax({
		type: "POST",
		url: "<?php echo Mage::getUrl('productmessage');?>",
		data: data,
		success: function(data){
			$j('#polcode_productmessage_form_container').html(data);
		},
	});
}

</script>
<div id="polcode_productmessage_form_container">
	<form  name="quickrfq_form" id="quickrfq_form"   method="post" enctype="multipart/form-data" name="quickrfq_form" action=""  >
		<table>
			<input type="hidden" id="product_name" name="product_name" value="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name');?>"/>
			<input type="hidden" id="product_mail" name="product_mail" value="<?php echo $_product->getEmail();?>"/>
			<input type="hidden" id="product_id" name="product_id" value="<?php echo $_product->getId();?>"/>
			<input type="hidden" id="category_name" name="category_name" value="<?php echo $this->getCategory();?>"/>
			<input type="hidden" id="subcategory_name" name="subcategory_name" value="<?php echo $this->getSubCategory();?>"/>
			<tr>
				<td><Strong>Nombre<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</strong></td>
				<td><input type="text" id="name" name="contact_name" size="40" class="text_wi"/><p></p></td>
			</tr>
			<tr>
				<td><Strong>E-mail<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</Strong></td>
				<td><input type="text" id="email" name="user_email" size="40" class="text_wi" /><p></p></td>
			</tr>
			<tr>
				<td><Strong>Tel&eacute;fono</Strong></td>
				<td><input type="text" id="telephone" name="telephone"size="40" class="text_wi" /><p></p></td>
			</tr>
			<tr>
				<td><Strong>Mensaje<font size=2 color="red"><b>*</b></font>&nbsp;&nbsp;</Strong></td>
				<td><textarea id="rfq_message" name="rfq_message" rows="8" cols="94" class="textarea_wi"></textarea><p></p></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit"  style="width:60px;" name="mailing_list" value="Enviar" class="submit_wi" onclick="return polcode_productmessage_validate();" id="polcode_productMessage_submitButton"></td>
			</tr>
		</table>		 
	</form>
</div>