<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php $mod = $this->getRequest()->getModuleName(); ?>
		<?php if($mod!="customer"):?>
			<div class="block">       
		<strong><?php echo $this->__('Main Categories') ?></strong>
			<div class="blockContent">
				<?php if($_menu): ?>
					<ul class="mainNav">
					  <?php //echo $_menu ?>
					  <?php foreach ($this->getStoreCategories() as $_category): ?>
                            <li><a href="<?php echo $this->getCategoryUrl($_category); ?>"><?php echo $this->htmlEscape($_category->getName()); ?></a></li>
                     <?php endforeach ?> 
					</ul>                
				<?php endif ?>
			</div>
		</div>        
		<?php endif; ?>
		